ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE balance_sp
DATAFILE 'balance01.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

CREATE USER balance IDENTIFIED BY "Balance#123"
DEFAULT TABLESPACE balance_sp
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON balance_sp;

GRANT CREATE SESSION TO balance;
GRANT CREATE TABLE TO balance;
GRANT CREATE SEQUENCE TO balance;
GRANT CREATE PROCEDURE TO balance;
GRANT CREATE TRIGGER TO balance;
