import type { Metadata } from "next";
import "./globals.css";
import TopMenu from "@/components/app/top-menu";
import React from "react";

export const metadata: Metadata = {
  title: "CRUD APP",
  description: "Generated by create next app",
};

export default function RootLayout({children} : {children : React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <TopMenu />

        <main className="px-8 py-4">
          {children}
        </main>
      </body>
    </html>
  );
}
